# typeform_invite.yaml
---
name: "typeform_invite"
pack: "st2-community"
enabled: true
description: "Write to DB and send invite on new user submission"
trigger:
  pack: "typeform"
  type: "typeform.registration"
criteria: {}
action:
  ref: community.register_and_invite
  parameters:
    registration_data: "{{trigger}}"
