# typeform_invite.yaml
---
name: "typeform_invite"
pack: "st2_community"
enabled: false
description: "Write to DB and send invite on new user submission"
trigger:
  pack: "typeform"
  type: "typeform.registration"
criteria: {}
action:
  ref: st2_community.register_and_invite
  parameters:
    registration_data: "{{trigger}}"
